language: scala

scala:
#  - 0.18.1
#  - 2.12.10
  - 2.13.1

env:
  - ADOPTOPENJDK=8     SCALAJS_VERSION=
#  - ADOPTOPENJDK=8     SCALAJS_VERSION=0.6.29
#  - ADOPTOPENJDK=8     SCALAJS_VERSION=1.0.0-M8
  - ADOPTOPENJDK=11    SCALAJS_VERSION=

# matrix:
#   exclude:
#     - scala: 0.18.1
#       env: ADOPTOPENJDK=8     SCALAJS_VERSION=0.6.29
#     - scala: 0.18.1
#       env: ADOPTOPENJDK=8     SCALAJS_VERSION=1.0.0-M8
#   include:
#     - scala: 2.11.12
#       env: ADOPTOPENJDK=8     SCALANATIVE_VERSION=0.3.9
#     - scala: 2.11.12
#       env: ADOPTOPENJDK=8     SCALANATIVE_VERSION=0.4.0-M2

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin/ ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdkJava=$(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - sdk install java $sdkJava || true # install fails if it's already installed
  - sdk use java $sdkJava
  - unset JAVA_HOME
  - if [[ $ADOPTOPENJDK == 8 ]]; then versionPrefix="1\.8" else versionPrefix=$ADOPTOPENJDK; fi
  - java -version 2>&1 | grep 'AdoptOpenJDK[^0-9]*$versionPrefix\.FAIL'
  - true

install:
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt            -name "*.lock"               | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
    - $HOME/.sdkman
