language: scala
jdk: openjdk8

jobs:
  include:
    - stage: build
      script:
        - sbt clean package
    - stage: rebuild
      script:
        - ./set-last-modified
        - sbt package

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - target/

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
