language: scala
jdk: openjdk8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2 expat
  - curl -O https://raw.githubusercontent.com/scala/graphviz-deb/master/graphviz_2.28.0-1_amd64.deb
  - sudo dpkg -i graphviz_2.28.0-1_amd64.deb

script:
  - dot -V
  - sbt doc
  - tar -czvf api.tgz target/scala-2.12/api
  - curl --upload-file ./api.tgz https://transfer.sh/api.tgz

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
