version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

dist: xenial  # GPG stuff breaks on bionic; scala/scala-dev#764
language: scala

stages:
  - build
  - test

build-tpl: &build-tpl
  name: build on pr / push 16
  script:
    - java -version
    - echo "hai" > file.txt
  workspaces:
    create:
      name: bootstrapped
      paths:
        - "file.txt"

test-tpl: &test-tpl
  name: test on pr / push 16
  workspaces:
    use: bootstrapped
  script:
    - java -version
    - cat file.txt


jobs:
    include:
      - stage: build
        if: type = push
        name: build on push
        script:
          - java -version

      - stage: test
        if: type = push
        name: test on push
        script:
          - java -version

      - stage: build
        <<: *build-tpl
        if: type = pull_request

      - stage: build
        <<: *build-tpl
        if: type = push
        env: ADOPTOPENJDK=16

      - stage: test
        <<: *test-tpl
        if: type = pull_request

      - stage: test
        <<: *test-tpl
        if: type = push
        env: ADOPTOPENJDK=16

      - stage: build
        name: speck
        language: ruby
        install:
          - ruby -v
        script:
          - echo "ok"

env:
  global:
    - ADOPTOPENJDK=8
