version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

dist: xenial  # GPG stuff breaks on bionic; scala/scala-dev#764
language: scala

# env:
#   - ADOPTOPENJDK=8
#   - ADOPTOPENJDK=16

stages:
  - build
  - test

jobs:
    include:
      - stage: build
        if: type = push
        name: build on push
        script:
          - java -version

      - stage: test
        if: type = push
        name: test on push
        script:
          - java -version

      - stage: build
        if: type = pull_request AND env(ADOPTOPENJDK) = 8 OR type = push AND env(ADOPTOPENJDK) = 16
        name: build on pr / push 16
        env:
          - ADOPTOPENJDK=8
          - ADOPTOPENJDK=16
        script:
          - java -version
          - echo "hai" > file.txt
        workspaces:
          create:
            name: bootstrapped
            paths:
              - "file.txt"

      - stage: test
        if: type = pull_request AND env(ADOPTOPENJDK) = 8 OR type = push AND env(ADOPTOPENJDK) = 16
        name: test on pr / push 16
        env:
          - ADOPTOPENJDK=8
          - ADOPTOPENJDK=16
        workspaces:
          use: bootstrapped
        script:
          - java -version
          - cat file.txt

      - stage: build
        name: speck
        language: ruby
        install:
          - ruby -v
        script:
          - echo "ok"

env:
  global:
    - ADOPTOPENJDK=8
